from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from src.db.init_db import init_db
from src.api.routes.health import router as health_router
from src.api.routes.dashboard import router as dashboard_router
from src.api.routes.review_page import router as review_page_router
from src.api.routes.sales_page import router as sales_page_router
from src.api.routes.request_compare import router as request_compare_router
from src.api.routes.request_auto_compare import router as request_auto_compare_router
from src.api.routes.sales import router as sales_router
from src.api.routes.db_status import router as db_status_router
from src.api.routes.deploy import router as deploy_router
from src.api.routes.system import router as system_router
from src.api.routes.ops import router as ops_router
from src.api.routes.documents import router as documents_router
from src.api.routes.bank import router as bank_router
from src.api.routes.customer_reconciliation import router as customer_reconciliation_router

init_db()
app = FastAPI(title="TLC Group Request Platform", version="0.31.1-dashboard-recovery")

@app.get("/")
def root():
    return RedirectResponse(url="/dashboard")

for r in (health_router, dashboard_router, review_page_router, sales_page_router, request_compare_router, request_auto_compare_router, sales_router, db_status_router, deploy_router, system_router, ops_router, documents_router, bank_router, customer_reconciliation_router):
    app.include_router(r)
from src.api.routes.request_compare_report import router as request_compare_report_router
app.include_router(request_compare_report_router)
from src.api.routes.request_pending_review import router as request_pending_review_router
app.include_router(request_pending_review_router)
from src.api.routes.request_pending_review_resolution import router as request_pending_review_resolution_router
app.include_router(request_pending_review_resolution_router)
from src.api.routes.formal_sales_ledger import router as formal_sales_ledger_router
app.include_router(formal_sales_ledger_router)
from src.api.routes.request_review_workbench import router as request_review_workbench_router
app.include_router(request_review_workbench_router)
from src.api.routes.multi_bank_import import router as multi_bank_import_router
app.include_router(multi_bank_import_router)
from src.api.routes.bank_import_ui import router as bank_import_ui_router
app.include_router(bank_import_ui_router)
from src.api.routes.tlc_code_master import router as tlc_code_master_router
app.include_router(tlc_code_master_router)
from src.api.routes.tlc_bank_account_profile import router as tlc_bank_account_profile_router
app.include_router(tlc_bank_account_profile_router)
from src.api.routes.tlc_customer_master import router as tlc_customer_master_router
app.include_router(tlc_customer_master_router)
from src.api.routes.customer_bank_name_matching import router as customer_bank_name_matching_router
app.include_router(customer_bank_name_matching_router)
from src.api.routes.customer_period_reconciliation import router as customer_period_reconciliation_router
app.include_router(customer_period_reconciliation_router)
from src.api.routes.customer_reconciliation_history import router as customer_reconciliation_history_router
app.include_router(customer_reconciliation_history_router)
from src.api.routes.customer_reconciliation_workbench import router as customer_reconciliation_workbench_router
app.include_router(customer_reconciliation_workbench_router)
from src.api.routes.tlc_batch_center import router as tlc_batch_center_router
app.include_router(tlc_batch_center_router)
from src.api.routes.tlc_batch_request_import import router as tlc_batch_request_import_router
app.include_router(tlc_batch_request_import_router)
from src.api.routes.tlc_batch_compare import router as tlc_batch_compare_router
app.include_router(tlc_batch_compare_router)
from src.api.routes.tlc_batch_error_center import router as tlc_batch_error_center_router
app.include_router(tlc_batch_error_center_router)
from src.api.routes.tlc_batch_review_center import router as tlc_batch_review_center_router
app.include_router(tlc_batch_review_center_router)
from src.api.routes.tlc_batch_sales_ledger_center import router as tlc_batch_sales_ledger_center_router
app.include_router(tlc_batch_sales_ledger_center_router)
from src.api.routes.tlc_batch_bank_center import router as tlc_batch_bank_center_router
app.include_router(tlc_batch_bank_center_router)
from src.api.routes.tlc_batch_reconciliation_center import router as tlc_batch_reconciliation_center_router
app.include_router(tlc_batch_reconciliation_center_router)
from src.api.routes.tlc_batch_lifecycle_overview import router as tlc_batch_lifecycle_overview_router
app.include_router(tlc_batch_lifecycle_overview_router)
from src.api.routes.tlc_import_center import router as tlc_import_center_router
app.include_router(tlc_import_center_router)
from src.api.routes.tlc_request_import_job_sync import router as tlc_request_import_job_sync_router
app.include_router(tlc_request_import_job_sync_router)
from src.api.routes.tlc_bank_csv_import_job import router as tlc_bank_csv_import_job_router
app.include_router(tlc_bank_csv_import_job_router)
from src.api.routes.tlc_bank_document_staging import router as tlc_bank_document_staging_router
app.include_router(tlc_bank_document_staging_router)
from src.api.routes.tlc_purchase_request_staging import router as tlc_purchase_request_staging_router
app.include_router(tlc_purchase_request_staging_router)
from src.api.routes.tlc_import_error_retry import router as tlc_import_error_retry_router
app.include_router(tlc_import_error_retry_router)
from src.api.routes.tlc_monthly_close_control import router as tlc_monthly_close_control_router
app.include_router(tlc_monthly_close_control_router)
from src.api.routes.tlc_monthly_close_checklist import router as tlc_monthly_close_checklist_router
app.include_router(tlc_monthly_close_checklist_router)
from src.api.routes.tlc_cross_month_carry_forward import router as tlc_cross_month_carry_forward_router
app.include_router(tlc_cross_month_carry_forward_router)
from src.api.routes.tlc_monthly_close_authorization import router as tlc_monthly_close_authorization_router
app.include_router(tlc_monthly_close_authorization_router)
from src.api.routes.tlc_operational_exception_dashboard import router as tlc_operational_exception_dashboard_router
app.include_router(tlc_operational_exception_dashboard_router)
from src.api.routes.tlc_business_operations_home import router as tlc_business_operations_home_router
app.include_router(tlc_business_operations_home_router)
from src.api.routes.tlc_guided_monthly_workflow import router as tlc_guided_monthly_workflow_router
app.include_router(tlc_guided_monthly_workflow_router)
from src.api.routes.tlc_end_to_end_readiness import router as tlc_end_to_end_readiness_router
app.include_router(tlc_end_to_end_readiness_router)
from src.api.routes.tlc_business_test_replay import router as tlc_business_test_replay_router
app.include_router(tlc_business_test_replay_router)
from src.api.routes.tlc_build035_acceptance import router as tlc_build035_acceptance_router
app.include_router(tlc_build035_acceptance_router)
from src.api.routes.tlc_customer_reconciliation_snapshot import router as tlc_customer_reconciliation_snapshot_router
from src.api.routes.tlc_customer_reconciliation_snapshot import page_router as tlc_customer_reconciliation_snapshot_page_router
app.include_router(tlc_customer_reconciliation_snapshot_router)
app.include_router(tlc_customer_reconciliation_snapshot_page_router)
from src.api.routes.tlc_customer_alias_matching import router as tlc_customer_alias_matching_router
from src.api.routes.tlc_customer_alias_matching import page_router as tlc_customer_alias_matching_page_router
app.include_router(tlc_customer_alias_matching_router)
app.include_router(tlc_customer_alias_matching_page_router)
from src.api.routes.tlc_sales_ledger_evidence import router as tlc_sales_ledger_evidence_router
from src.api.routes.tlc_sales_ledger_evidence import page_router as tlc_sales_ledger_evidence_page_router
app.include_router(tlc_sales_ledger_evidence_router)
app.include_router(tlc_sales_ledger_evidence_page_router)
from src.api.routes.tlc_bank_payment_evidence import router as tlc_bank_payment_evidence_router
from src.api.routes.tlc_bank_payment_evidence import page_router as tlc_bank_payment_evidence_page_router
app.include_router(tlc_bank_payment_evidence_router)
app.include_router(tlc_bank_payment_evidence_page_router)
from src.api.routes.tlc_customer_reconciliation_confirmation import router as tlc_customer_reconciliation_confirmation_router
from src.api.routes.tlc_customer_reconciliation_confirmation import page_router as tlc_customer_reconciliation_confirmation_page_router
app.include_router(tlc_customer_reconciliation_confirmation_router)
app.include_router(tlc_customer_reconciliation_confirmation_page_router)
from src.api.routes.tlc_customer_reconciliation_case import router as tlc_customer_reconciliation_case_router
from src.api.routes.tlc_customer_reconciliation_case import page_router as tlc_customer_reconciliation_case_page_router
from src.api.routes.tlc_customer_auto_matching import router as tlc_customer_auto_matching_router
from src.api.routes.tlc_customer_auto_matching import page_router as tlc_customer_auto_matching_page_router
app.include_router(tlc_customer_reconciliation_case_router)
app.include_router(tlc_customer_reconciliation_case_page_router)
app.include_router(tlc_customer_auto_matching_router)
app.include_router(tlc_customer_auto_matching_page_router)
from src.api.routes.tlc_customer_recommended_matching import router as tlc_customer_recommended_matching_router
from src.api.routes.tlc_customer_recommended_matching import page_router as tlc_customer_recommended_matching_page_router
app.include_router(tlc_customer_recommended_matching_router)
app.include_router(tlc_customer_recommended_matching_page_router)
from src.api.routes.request_folder_settings import router as request_folder_settings_router
from src.api.routes.request_folder_settings import page_router as request_folder_settings_page_router
app.include_router(request_folder_settings_router)
app.include_router(request_folder_settings_page_router)
