from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,Numeric,String,Text,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column
from src.db.base import Base
class LegalEntityORM(Base):
    __tablename__='legal_entities'; id:Mapped[str]=mapped_column(String(50),primary_key=True); name:Mapped[str]=mapped_column(String(200)); country:Mapped[str]=mapped_column(String(10)); language:Mapped[str]=mapped_column(String(10),default='zh'); created_at=mapped_column(DateTime(timezone=True),server_default=func.now())
class SalesRecordORM(Base):
    __tablename__='sales_records'; __table_args__=(UniqueConstraint('legal_entity_id','request_no',name='uq_sales_entity_request_no'),)
    id:Mapped[str]=mapped_column(String(64),primary_key=True); legal_entity_id:Mapped[str]=mapped_column(String(50),ForeignKey('legal_entities.id')); request_no:Mapped[str]=mapped_column(String(100)); sales_date=mapped_column(Date,nullable=True); customer_name:Mapped[str]=mapped_column(String(300),default=''); currency:Mapped[str]=mapped_column(String(10),default='JPY'); subtotal=mapped_column(Numeric(18,2),default=0); tax_amount=mapped_column(Numeric(18,2),default=0); total_amount=mapped_column(Numeric(18,2),default=0); status:Mapped[str]=mapped_column(String(50),default='posted'); created_at=mapped_column(DateTime(timezone=True),server_default=func.now())
class RequestCompareRunORM(Base):
    __tablename__='request_compare_runs'; id:Mapped[str]=mapped_column(String(64),primary_key=True); legal_entity_id:Mapped[str]=mapped_column(String(50),ForeignKey('legal_entities.id')); request_no:Mapped[str]=mapped_column(String(100)); status:Mapped[str]=mapped_column(String(50)); pdf_snapshot:Mapped[dict]=mapped_column(JSON); excel_snapshot:Mapped[dict]=mapped_column(JSON); difference_count:Mapped[int]=mapped_column(Integer,default=0); created_at=mapped_column(DateTime(timezone=True),server_default=func.now())
class ReviewTaskORM(Base):
    __tablename__='review_tasks'; id:Mapped[str]=mapped_column(String(64),primary_key=True); legal_entity_id:Mapped[str]=mapped_column(String(50),ForeignKey('legal_entities.id')); task_type:Mapped[str]=mapped_column(String(50)); business_key:Mapped[str]=mapped_column(String(200)); status:Mapped[str]=mapped_column(String(50),default='open'); priority:Mapped[str]=mapped_column(String(20),default='normal'); title_zh:Mapped[str]=mapped_column(String(500)); title_ja:Mapped[str]=mapped_column(String(500),default=''); detail_json:Mapped[dict]=mapped_column(JSON); assignee:Mapped[str]=mapped_column(String(200),default=''); resolution_note:Mapped[str]=mapped_column(Text,default=''); created_at=mapped_column(DateTime(timezone=True),server_default=func.now()); resolved_at=mapped_column(DateTime(timezone=True),nullable=True)
